CREATE TABLE users (
 id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(255) NOT NULL,
 password VARCHAR(255) NOT NULL,
 name VARCHAR(255)  NULL,
 created_at TIMESTAMP NOT NULL DEFAULT NOW(),
 last_login TIMESTAMP NULL
)